name: tenjin_plugin
description: A Flutter plugin to Tenjin SDK
version: 1.2.3
homepage: https://github.com/tenjin/tenjin-flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  lint: ^1.5.2
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.tenjin_sdk
        pluginClass: TenjinSdkPlugin
      ios:
        pluginClass: TenjinSdkPlugin
